---
title: "Visualizations"
output: html_document
---
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# MPC summary based on calibrated models


```{r setup, include=FALSE}
# python set up
library(reticulate)
knitr::knit_engines$set(python = reticulate::eng_python)

# import RData files (faster)
#load('data/generated/mpc_analysis.RData')
#load('data/generated/final_models.RData')

library(knitr)
```

## Generate summary statistics & graphs
```{r message=FALSE, warning=FALSE}
source("R/04_mpc_analysis.R")

```


## Wealth targeted vs. estimated distrubtions
```{r, echo= FALSE, message = FALSE}
kable(distributions_mat)
```

## Betas and MPCs
```{r, echo= FALSE, message = FALSE}
kable(mpcs_beta_mat_ind)
```

## Policy function
```{r}
mpc_analysis$policies_fi
```


## MPCs vs. Ginis
```{r warning=FALSE}
mpc_analysis$mpc_vs_gini
```


## Distribution of MPCs
```{python vplot}
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

mpcs_wide = r.mpcs_wide
# Save data frame
#import pickle
#with open("data/generated/mpcs.pkl", 'wb') as output:
#    pickle.dump(r.mpcs_wide, output)

# draw vplots
sns.set_style("whitegrid")
countries_per_plot = 2
for countries in np.split(mpcs_wide.Country.unique(), countries_per_plot):
    fig, ax = plt.subplots(figsize=(7, 2.5)) # size
    mpc_vplot = sns.violinplot(
        data=mpcs_wide[mpcs_wide["Country"].isin(countries)], 
        x="Country", y="MPC", hue="Estimate",
        inner="quartile",  # box (default) looks prettier but unclear interpertation
        split=True,  # show offshore and non-offshore side-by-side
        #cut=0,  # limit density to observed values, i.e. in [0, 1]
        bw="scott", gridsize=100,  # standard kernel estimation parameters
        ax = ax
    )
    mpc_vplot.set_ylim(bottom=0, top=1) # limit the MPC axis to [0, 1]
    mpc_vplot.legend(title=None, frameon=True, loc=4) # nicer legend
    plt.show()
```

